// src/svelte/AgentablePanel.svelte
<script lang="ts">
  /**
   * Svelte wrapper for `<agentable-panel>` ().
   */
  import { onDestroy, onMount } from 'svelte';
  import '../embed/agentable-panel';
  import type { AgentablePanelElement } from '../embed/agentable-panel';
  import {
    applyAgentablePanelProps,
    bindAgentablePanelEvents,
    type AgentablePanelEventHandlers,
    type AgentablePanelWrapperProps,
  } from '../embed/wrappers/agentablePanelWrapperCore';

  export let panel: string;
  export let tenant: string | undefined = undefined;
  export let primaryColor: string | undefined = undefined;
  export let welcomeMessage: string | undefined = undefined;
  export let apiEndpoint: string | undefined = undefined;
  export let anonKey: string | undefined = undefined;
  export let configPath: string | undefined = undefined;
  export let voiceEnabled: boolean | undefined = undefined;
  export let snapGrid: boolean | undefined = undefined;
  export let systemPrompt: string | undefined = undefined;
  export let voiceGreeting: string | undefined = undefined;
  export let greetingMode: string | undefined = undefined;
  export let tokenEndpoint: string | undefined = undefined;
  export let locale: string | undefined = undefined;
  export let configUrl: string | undefined = undefined;
  export let panelDataUrl: string | undefined = undefined;
  export let panelTitle: string | undefined = undefined;
  export let hideChrome: boolean | undefined = undefined;
  export let slotName: string | undefined = undefined;
  export let lazyHydrate: boolean | undefined = undefined;
  export let className: string | undefined = undefined;
  export let style: string | undefined = undefined;

  export let onConfigReloaded: AgentablePanelEventHandlers['onConfigReloaded'] = undefined;
  export let onPanelReady: AgentablePanelEventHandlers['onPanelReady'] = undefined;
  export let onAdapterLoaded: AgentablePanelEventHandlers['onAdapterLoaded'] = undefined;
  export let onPanelError: AgentablePanelEventHandlers['onPanelError'] = undefined;
  export let onChromeChanged: AgentablePanelEventHandlers['onChromeChanged'] = undefined;
  export let onApprovalPending: AgentablePanelEventHandlers['onApprovalPending'] = undefined;
  export let onPhaseChanged: AgentablePanelEventHandlers['onPhaseChanged'] = undefined;

  let panelEl: AgentablePanelElement | undefined;
  let unbindEvents: (() => void) | null = null;

  function wrapperProps(): AgentablePanelWrapperProps {
    return {
      panel,
      tenant,
      primaryColor,
      welcomeMessage,
      apiEndpoint,
      anonKey,
      configPath,
      voiceEnabled,
      snapGrid,
      systemPrompt,
      voiceGreeting,
      greetingMode,
      tokenEndpoint,
      locale,
      configUrl,
      panelDataUrl,
      panelTitle,
      hideChrome,
      slotName,
      lazyHydrate,
    };
  }

  function eventHandlers(): AgentablePanelEventHandlers {
    return {
      onConfigReloaded,
      onPanelReady,
      onAdapterLoaded,
      onPanelError,
      onChromeChanged,
      onApprovalPending,
      onPhaseChanged,
    };
  }

  function syncElement(): void {
    if (!panelEl) {
      return;
    }
    applyAgentablePanelProps(panelEl, wrapperProps());
  }

  onMount(() => {
    if (!panelEl) {
      return;
    }
    syncElement();
    unbindEvents = bindAgentablePanelEvents(panelEl, eventHandlers);
  });

  onDestroy(() => {
    unbindEvents?.();
    unbindEvents = null;
  });

  $: if (panelEl) {
    syncElement();
  }

  export function reload(): Promise<void> {
    if (!panelEl) {
      return Promise.resolve();
    }
    return panelEl.reload();
  }

  export function getElement(): AgentablePanelElement | undefined {
    return panelEl;
  }
</script>

<agentable-panel
  bind:this={panelEl}
  class={className}
  {style}
  {panel}
  {tenant}
  primary-color={primaryColor}
  welcome-message={welcomeMessage}
  api-endpoint={apiEndpoint}
  anon-key={anonKey}
  config-path={configPath}
  voice-enabled={voiceEnabled}
  snap-grid={snapGrid}
  system-prompt={systemPrompt}
  voice-greeting={voiceGreeting}
  voice-greeting-mode={greetingMode}
  token-endpoint={tokenEndpoint}
  {locale}
  config-url={configUrl}
  panel-data-url={panelDataUrl}
  panel-title={panelTitle}
  hide-chrome={hideChrome}
  slot-name={slotName}
  lazy-hydrate={lazyHydrate}
>
  <slot />
</agentable-panel>

// src/vue/AgentablePanel.vue
<script setup lang="ts">
/**
 * Vue 3 wrapper for `<agentable-panel>` ().
 */
import { onBeforeUnmount, onMounted, ref, watch } from 'vue';
import '../embed/agentable-panel';
import type { AgentablePanelElement } from '../embed/agentable-panel';
import {
  applyAgentablePanelProps,
  bindAgentablePanelEvents,
  type AgentablePanelEventHandlers,
  type AgentablePanelWrapperProps,
} from '../embed/wrappers/agentablePanelWrapperCore';

const props = withDefaults(
  defineProps<
    AgentablePanelWrapperProps & {
      class?: string;
      style?: string | Record<string, string>;
    }
  >(),
  {
    panel: '',
  });

const emit = defineEmits<{
  configReloaded: [event: CustomEvent];
  panelReady: [event: CustomEvent];
  adapterLoaded: [event: CustomEvent];
  panelError: [event: CustomEvent];
  chromeChanged: [event: CustomEvent];
  approvalPending: [event: CustomEvent];
  phaseChanged: [event: CustomEvent];
}>();

const panelRef = ref<AgentablePanelElement | null>(null);
let unbindEvents: (() => void) | null = null;

function wrapperPropsFromVue(): AgentablePanelWrapperProps {
  return {
    panel: props.panel,
    tenant: props.tenant,
    primaryColor: props.primaryColor,
    welcomeMessage: props.welcomeMessage,
    apiEndpoint: props.apiEndpoint,
    anonKey: props.anonKey,
    configPath: props.configPath,
    voiceEnabled: props.voiceEnabled,
    snapGrid: props.snapGrid,
    systemPrompt: props.systemPrompt,
    voiceGreeting: props.voiceGreeting,
    greetingMode: props.greetingMode,
    tokenEndpoint: props.tokenEndpoint,
    locale: props.locale,
    configUrl: props.configUrl,
    panelDataUrl: props.panelDataUrl,
    panelTitle: props.panelTitle,
    hideChrome: props.hideChrome,
    slotName: props.slotName,
    lazyHydrate: props.lazyHydrate,
  };
}

function eventHandlersFromEmit(): AgentablePanelEventHandlers {
  return {
    onConfigReloaded: (event) => emit('configReloaded', event),
    onPanelReady: (event) => emit('panelReady', event),
    onAdapterLoaded: (event) => emit('adapterLoaded', event),
    onPanelError: (event) => emit('panelError', event),
    onChromeChanged: (event) => emit('chromeChanged', event),
    onApprovalPending: (event) => emit('approvalPending', event),
    onPhaseChanged: (event) => emit('phaseChanged', event),
  };
}

function syncElement(): void {
  if (!panelRef.value) {
    return;
  }
  applyAgentablePanelProps(panelRef.value, wrapperPropsFromVue());
}

onMounted(() => {
  if (!panelRef.value) {
    return;
  }
  syncElement();
  unbindEvents = bindAgentablePanelEvents(panelRef.value, eventHandlersFromEmit);
});

watch(
  () => wrapperPropsFromVue(),
  () => syncElement(),
  { deep: true });

onBeforeUnmount(() => {
  unbindEvents?.();
  unbindEvents = null;
});

async function reload(): Promise<void> {
  if (panelRef.value) {
    await panelRef.value.reload();
  }
}

defineExpose({
  get element() {
    return panelRef.value;
  },
  reload,
});
</script>

<template>
  <agentable-panel
    ref="panelRef":class="props.class":style="props.style":panel="props.panel":tenant="props.tenant":primary-color="props.primaryColor":welcome-message="props.welcomeMessage":api-endpoint="props.apiEndpoint":anon-key="props.anonKey":config-path="props.configPath":voice-enabled="props.voiceEnabled":snap-grid="props.snapGrid":system-prompt="props.systemPrompt":voice-greeting="props.voiceGreeting":voice-greeting-mode="props.greetingMode":token-endpoint="props.tokenEndpoint":locale="props.locale":config-url="props.configUrl":panel-data-url="props.panelDataUrl":panel-title="props.panelTitle":hide-chrome="props.hideChrome":slot-name="props.slotName":lazy-hydrate="props.lazyHydrate"
  >
    <slot />
  </agentable-panel>
</template>
